### ISSUE TITLE
error: Class 'typedlinkfield\fields\LinkField' not found 

### ISSUE THREAD

**Issue by Jones-S** [sebastian-lenz/craft-linkfield#122]
I just migrated to another server and updated some dependencies. When running `/.craft project-config/apply` I get the following error:
`error: Class 'typedlinkfield\fields\LinkField' not found `

Does that tell you anything? I am a bit lost how to debug that...

Thanks for any help.
Cheers

```
"require": {
    "php": "7.0.* || 7.1.* || 7.2.*",
    "craftcms/cms": "^3.5.2",
    "craftcms/element-api": "2.6.0",
    "craftcms/redactor": "2.6.0.1",
    "mmikkel/cp-field-inspect": "1.1.2",
    "nystudio107/craft-seomatic": "^3.2.43",
    "putyourlightson/craft-cp-style-guide": "1.0.2",
    "sebastianlenz/linkfield": "2.0.x-dev",
    "spicyweb/craft-neo": "^2.6.1",
    "verbb/field-manager": "2.1.1",
    "vlucas/phpdotenv": "^2.4.0"
  },
```

**Comment by Jones-S** [comment]
Oh I see. I think I had to update that the old linkField type could not be found. I think I have to adjust all linkfield fields hoping the data would stay in place...:S

**Comment by sebastian-lenz** [comment]
Hi @Jones-S, thanks for reporting this. I assume that something on the Craft side has changed in the latest versions as I am not aware of this issue on the upgrade path.

**Comment by curtishenson** [comment]
I unfortunately don't have anything to add about the source of this. But rebuilding the project config locally was a pretty easy fix for me.

For some reason the type key in project config was `type: typedlinkfield\fields\LinkField` instead of `type: lenz\linkfield\fields\LinkField`. Seemed like my project-config was for v1, even though in commits I can see it updated. 🤷

**Comment by sebastian-lenz** [comment]
Okay, I've added a legacy class `typedlinkfield\fields\LinkField` that extends `lenz\linkfield\fields\LinkField` and generates a deprecation error.

**Comment by michtio** [comment]
@sebastian-lenz 

Rebuilding the PC or going in the field and resaving doesn't change a thing...
This update broke FeedMe imports

**Comment by DynamiteGoesBoom** [comment]
@sebastian-lenz any update to @michtio's report on FeedMe?

**Comment by timkelty** [comment]
Getting the same error in feedme

**Comment by timkelty** [comment]
@DynamiteGoesBoom @michtio you can hack around this by sticking this in project somewhere (eg `config/app.php`):

```php
class_alias(\lenz\linkfield\fields\LinkField::class, '\typedlinkfield\fields\LinkField');
```

**Comment by sebastian-lenz** [comment]
Hm, okay, I've added a proxy class [here](https://github.com/sebastian-lenz/craft-linkfield/blob/master/legacy/fields/LinkField.php) and I've added a composer autload entry [here](https://github.com/sebastian-lenz/craft-linkfield/blob/master/composer.json#L16). On my local install I also see the class `typedlinkfield\\fields\\LinkField` in my generted composer class loader, so there should be no need to alias something here?

Does the problem occur on the latest v2 version?

**Comment by timkelty** [comment]
@sebastian-lenz I'll try the latest…but it should really be fixed in feed-me anyhow…
PR here: https://github.com/sebastian-lenz/craft-linkfield/issues/122

**Comment by sebastian-lenz** [comment]
Okay, I've added support for FeedMe to the plugin, you'll now see more available field mappings when using the link field with FeedMe. I hope this resolves this issue, besides the already included dummy class.

As this issue already is quite long and discusses different problems, I'll close it for now. Thank you all for your help and please feel free to open a new issue should you run into any problems.

**Comment by Maybach91** [comment]
I still get an Deprecation Warning, Rebuilding Project Config did not solved this. Using `2.0.0-rc.1`

With the following message:
```
Using of the legacy link field class is deprecated. The project configuration might need a rebuild, see https://github.com/sebastian-lenz/craft-linkfield/issues/122 | /var/www/virtual/kf/deploy/releases/3a894351b9ebaae214df2cef07621c5aaa6d7fae/vendor/composer/ClassLoader.php:480

```

**Comment by Maybach91** [comment]
Any suggestions how to fix the deprecation warning ↑ ? @sebastian-lenz ?

**Comment by jonathanmelville** [comment]
Also getting the deprecation warning on v2.

**Comment by Maybach91** [comment]
@sebastian-lenz ping

**Comment by wuhhh** [comment]
Getting deprecation warning on Craft 3.7.30.1, plugin 2.0.0-rc.1

**Comment by darylknight** [comment]
Subscribing. Seeing this deprecation error in Craft 4 with Link Field 2.1.3-rc

**Comment by MateuszEckardt** [comment]
@darylknight Same for me. Latest `craft: 4.0.5.1` with `linkfield: 2.1.3-rc`.
---
Something peculiar in my case - I have other projects that 'run' basically the same config and somehow there is no deprecation warning there. Trying to debug this. I'll try to post more info if I find something.

**Comment by MateuszEckardt** [comment]
Ok - I am back with some information:

I managed to solve the deprecation error in my project. Here is what I did: 
- I went back and started checking every link field that I had 
- Found out that in 2 places the fields had wrong field type. They were - to my surprise - shown as assets and not as link fields
- I switched back to link field type, adjusted the settings accordingly
- When I removed the deprecation warning and reloaded the page - deprecation was gone, no errors

Now as to why the link fields were shown as assets - I have no idea what could've gone wrong at this point.

I migrated to Craft 4 about a month ago but for the life of me I cannot recall if that deprecation error was present since then or is it more recent...

P.S.
I took the liberty of tagging people who recently encountered this issue - hoping that it'll help you out.
@Jones-S @curtishenson  @michtio @timkelty @darylknight @Maybach91 @wuhhh @jonathanmelville and of course @sebastian-lenz

**Comment by darylknight** [comment]
I also managed to fix this on a site by rebuilding project config after updating to Craft 4.

**Comment by michtio** [comment]
Thank you @MateuszEckardt for taking the time :)

**Comment by jacksutherland** [comment]
Getting this as well now after upgrading to Craft 4 with Link Field 2.1.3-rc. Surprised it's still an issue after this long. Unfortunately, I still get it after rebuilding my project config. Is there still no resolution?

**Comment by jacksutherland** [comment]
@MateuszEckardt you were spot on! I was just able to reproduce your steps. Except in my case, every single link field had changed to Assets. The plugin's link type field defaults to Assets, so maybe that has something to do with it??

But this really should get fixed, as it has pretty big ramifications and potential for data loss.

**Comment by DavidKabelitz** [comment]
After updating to Craft 4 i got that error and link to that ticket...
Using of the legacy link field class is deprecated. The project configuration might need a rebuild, see https://github.com/sebastian-lenz/craft-linkfield/issues/122

Rebuilding the project config does not solve it...

**Comment by aaronrobb** [comment]
Getting the same issue as @DavidKabelitz when trying to update to Craft 4.

Tried rebuilding the config but then I get:

```
Rebuilding the project config from the current state ... error: Using of the legacy link field class is deprecated.
The project configuration might need a rebuild, see https://github.com/sebastian-lenz/craft-linkfield/issues/122
```

So the suggestion that we need to rebuild the config as the solution to the error while rebuilding the config is not too helpful. 

Is there another way around this? I'm mid-way through a migration to Craft 4, so I can't even get into the admin area to check fields/settings in there.

**Comment by aaronrobb** [comment]
Update:
I worked around this issue by disabling the exceptions on deprecation warnings.
In my case, it was in the config/app.php file - I had a deprecator running that I commented out:

```
"components" => [
            "deprecator" => [
                //"throwExceptions" => true,
            ],
        ],
```

**Comment by darylknight** [comment]
Ran into this today on a site, this time it wouldn't go away just by rebuilding. Following the thread above, I did indeed find 4 fields that were listed as "Asset" that used to be link fields. They're all inside a Matrix block, and when I tried to change them back from Assets to Link fields, I got this error:

![image](https://user-images.githubusercontent.com/1250017/200562428-d7294c3d-bcaf-480c-9a8d-9243f56f8384.png)

Can't find a way around it.

**Comment by ce2cs** [comment]
> Ran into this today on a site, this time it wouldn't go away just by rebuilding. Following the thread above, I did indeed find 4 fields that were listed as "Asset" that used to be link fields. They're all inside a Matrix block, and when I tried to change them back from Assets to Link fields, I got this error:
> 
> ![image](https://user-images.githubusercontent.com/1250017/200562428-d7294c3d-bcaf-480c-9a8d-9243f56f8384.png)
> 
> Can't find a way around it.

Same, link field inside matrix block will change to assets. But still shows linkField in the config file

**Comment by ctangney-tulip** [comment]
Following up on this --

In our local development environment (Craft 4.x / plugin version 3.1) we also identified that our link fields were incorrectly set to `Asset` type. This was observed during the process of updating from Craft 3.x to Craft 4.x.

Further digging into the `.yaml` revealed that the type for these fields _had not been reset_. Immediately, we grew suspicious of the migration file `[m190417_202153_migrateDataToTable.php](https://github.com/sebastian-lenz/craft-linkfield/blob/4b86a33869402c8312d47fbffaa06155e4283023/src/migrations/m190417_202153_migrateDataToTable.php#L64)` -- specifically lines `64`, `66`, and `72`.

Performing this query against our database (`SELECT * from TABLE where type = 'typedlinkfield\fields\LinkField';`) returned 0 records _as a result of the unescaped back slashes_. Properly escaping the back slashes and performing the query again returned the correct / expected result.

After updating these lines in the migration file, and re-running the migration for this plugin, the deprecation warning in the Craft Admin UI is no longer present, and all `.yaml` files have had their type properly reset.

This process was successfully tested against multiple developer's machines. 

If you don't mind, would you be able to see if this fixes your issue as well, [darylknight](https://github.com/darylknight)?

If this is in fact the problem, I will be more than happy to open a new issue and submit a PR @sebastian-lenz

**Comment by darylknight** [comment]
Do you know what the correct command is to run?

`SELECT * from craft_matrixcontent_contentmatrix where type = 'typedlinkfield\\fields\\LinkField';`
`Query 1 ERROR: Unknown column 'type' in 'where clause'`

`SELECT * from craft_matrixcontent_contentmatrix where type = 'typedlinkfield\\fields\\LinkField';`
`Query 1 ERROR: Unknown column 'type' in 'where clause'`

**Comment by darylknight** [comment]
How do you re-run the migration?

![image](https://user-images.githubusercontent.com/1250017/201983550-7c531d9f-44ab-435c-a792-f8760f9948c1.png)

**Comment by ctangney-tulip** [comment]
@darylknight this will be unique by environment, but typically this can be done by restoring from a backup taken from before the migrations have been run.

In our instance, we are restoring from a production environment running an older version of Craft / link field. Once we have restored this data, we _have_ to migrate forward in order to be compatible with Craft 4 (our own semantics 😅)

**Comment by joshuarichard** [comment]
+1 to @ctangney-tulip's solution on the case of the incorrect field types. The [craft docs](https://docs.craftcms.com/api/v4/craft-db-migration.html#method-update) explicitly say they'll escape the column names but say nothing about column values. The `where` docs (the function that `update` calls) also don't mention anything about value escaping.

**Comment by darylknight** [comment]
Sorry, I don't have a backup of this site from Craft 3. I did try updating the migration and running it again with a backup from last month, which ran all the migrations, but the deprecation warning is still there and won't go away. This is what I updated those lines to before running it again:

![image](https://user-images.githubusercontent.com/1250017/202130219-2a9a1922-7775-421e-9a11-d900fdbb7d57.png)

**Comment by ctangney-tulip** [comment]
@darylknight it will be necessary for you to clear your existing deprecation warnings after you have run the migration, then load the page on which the deprecation was occurring. Have you done this?

**Comment by darylknight** [comment]
Yes. This deprecation has never happened on a traceable template for me. The location is this: 

![image](https://user-images.githubusercontent.com/1250017/202205472-2156ec12-6289-4f95-86a3-e1b07070864b.png)

**Comment by ctangney-tulip** [comment]
This is also the location which our error was stemming from. Would you be able to locate one of your link field `.yaml` files and confirm that the type is correctly set to `typedlinkfield\fields\LinkField`?

<img width="719" alt="image" src="https://user-images.githubusercontent.com/107075008/202208256-53f0f50e-fb55-42db-ad8f-4aa2ce3f58c7.png">

These files would probably be in a location like `~/config/project/fields/`.

**Comment by darylknight** [comment]
![image](https://user-images.githubusercontent.com/1250017/202222827-b91717fc-d4b1-4f9a-8032-4b9c6111800f.png)

**Comment by ctangney-tulip** [comment]
Eep! I misspoke previously. I've gone back and updated my comment to reflect the correct type (I have not yet had my coffee 😅) It looks to me like these `.yaml` files are still reflecting the old name. I am wondering if the migration ran correctly. The correct type would be `lenz\linkfield\fields\LinkField`.

I might try manually updating these types to be `lenz\linkfield\fields\LinkField` then rebuilding your config from the yaml via the admin UI to see if this resolves your deprecation error.

**Comment by darylknight** [comment]
Sorry I'm having too many issues trying to roll this site back to run those migrations again. It sounds like that solution would solve the problem, but only for sites that haven't already upgraded to Craft 4.

**Comment by chrisrowe** [comment]
I ran into this just now. Editing the migration to double `\\`, and running `./craft migrate/up --plugin typedlinkfield` before all other migrations worked

**Comment by ctangney-tulip** [comment]
Excellent, thanks for confirming that worked for you @chrisrowe!

I'll see about opening a new issue and cutting a pull request at some point today 🤘

**Comment by mateostabio** [comment]
Also happening to me, I just successfully updated a client site to Craft CMS 4.4.5, and getting this error.

![Screenshot 2023-03-24 at 5 03 00 PM](https://user-images.githubusercontent.com/5912721/227640573-36244435-b30e-49f1-8fc0-edaeeebe776c.png)

Can't seem to get it to go away. Anyone find a fix?

**Comment by DavidKabelitz** [comment]
the same for me still on all projects!

**Comment by chrisrowe** [comment]
Hyper is always an option if y’all are desperate

**Comment by mateostabio** [comment]
@chrisrowe can you explain hyper?

**Comment by chrisrowe** [comment]
https://verbb.io/craft-plugins/hyper/features

It supports migrations from linkfield

**Comment by MargaritaBusyginaCa** [comment]
I was getting the deprecation warning after upgrading to Craft 4 and nothing helped except performing the upgrade once again. The second time I upgraded from Craft 3 to Craft 4 the depreciation warning was gone.

**Comment by CreateSean** [comment]
I'm running into this issue on a craft 4.5.6.1 site. I've rebuilt project config but the deprecation warning continues to surface.

Please advise.

**Comment by estebancastro** [comment]
> I was getting the deprecation warning after upgrading to Craft 4 and nothing helped except performing the upgrade once again. The second time I upgraded from Craft 3 to Craft 4 the depreciation warning was gone.

Same here, I got the warning after upgrading to 4.

How do you upgraded twice the same project? "the second time" I don't get it.

**Comment by MargaritaBusyginaCa** [comment]
@estebancastro 
By going back to Craft 3 and upgrading to Craft 4 again. In my case, I went back to the branch with Craft 3, created a new branch and updated to Craft 4 there. And then the warning was gone.
