### ISSUE TITLE
Craft 3.4-RC1.1 Error: Could not render the template for the field `x`

### ISSUE THREAD

**Issue by gijsstegehuis** [sebastian-lenz/craft-linkfield#87]
See screenshot. Since updating to Craft 3.4-RC1.1 i'm getting these errors.
It translates to: "Could not render the template for the field x"

<img width="620" alt="Schermafbeelding 2020-01-16 om 11 48 38" src="https://user-images.githubusercontent.com/5496039/72518735-35d95580-3856-11ea-8fde-c0f5068582f0.png">

**Comment by sebastian-lenz** [comment]
Which version of the plugin are you using?

**Comment by gijsstegehuis** [comment]
I am on 1.0.19

**Comment by Wiejeben** [comment]
Does this error persist when updating to the stable release of Craft 3.4?

**Comment by sebastian-lenz** [comment]
I cannot reproduce this issue in the released version of Craft 3.4. Has anyone else this prblem?

**Comment by Mosnar** [comment]
For what it's worth, I haven't had any issues on Craft 3.4.1 + Typed Link Field 1.0.19

v2-beta.6 on the other hand is not functioning on Craft 3.4.1

**Comment by sebastian-lenz** [comment]
@Mosnar Thanks for the feedback. I'm playing around in Craft 3.4 with v2 of the field and haven't found an issue so far, but I am using the most current dev version. I've released all dev changes as v2-beta.7 right now. If you see any issues with this version as well, please send me over your issues so I can check on them.

**Comment by Mosnar** [comment]
Thanks - beta 7 didn't solve the issue, but I uninstalled and reinstalled all of my plugins and it seems to have fixed the issue. The error was something about the typedlinkfield translation category not existing, so I'm assuming something is causing an unusual race condition.

**Comment by sebastian-lenz** [comment]
Okay, I assume the original issue to be resolved, I could not reproduce over the course of the last week.
